### ISSUE TITLE
allow to send shutdown communication through CLI

### ISSUE THREAD

**Issue by job** [job/openbgpd#1]
You can shut a neighbor via the CLI, the additional argument `Groeten van henk` should be the shutdown communication send to the peer or the group of peers

```
[job@kiera ~]$ bgpctl neighbor 165.254.255.16 down "Groeten van henk"
superfluous argument: Groeten van henk
```

**Comment by Habbie** [comment]
c18bfe7cb3c6c0aeeffd7978ef40ed253d3e158e reports 'bgpd shutdown' as a message

**Comment by Habbie** [comment]
d78da2987e6d0881f9bad65b69d22074199256ab adds 'groeten van henk'

**Comment by Habbie** [comment]
bgpctl side finished in d5d298f. Exabgp now chokes on what we send out if there is no down reason, probably my fault. Leaving open for that.

**Comment by Habbie** [comment]
Exabgp chokes on a zero-length communication, which is a bug in exabgp.

**Comment by Habbie** [comment]
(should not send in that case though)

**Comment by Habbie** [comment]
Don't immediately spot the bug in the exa code - keeping this open.

**Comment by job** [comment]
openbgpd sends:

```
    165.254.255.26.179 > 165.254.255.16.57440: Flags [P.], cksum 0x4a6e (incorrect -> 0xd333), seq 73:104, ack 175, win 2172, options [nop,nop,TS val 2411508788 ecr 980763100], length 31: BGP, length: 31
	Notification Message (3), length: 31, Cease (6), subcode Administratively Shutdown (2)
	0x0000:  45c0 0053 f15d 4000 ff06 3f5e a5fe ff1a  E..S.]@...?^....
	0x0010:  a5fe ff10 00b3 e060 09a4 16fa e606 99bf  .......`........
	0x0020:  8018 087c 4a6e 0000 0101 080a 8fbc b434  ...|Jn.........4
	0x0030:  3a75 41dc ffff ffff ffff ffff ffff ffff  :uA.............
	0x0040:  ffff ffff 001f 0306 0209 3132 3334 3536  ..........123456
	0x0050:  3738 39                                  789
```

exa prints: ```Sat, 31 Dec 2016 00:57:42 | INFO     | 28607  | network       | Peer  165.254.255.26 ASN 15562   out loop, peer reset, message [notification received (6,2)] error[Cease / Administrative Shutdown / Shutdown Communication: "12345678"]```

**Comment by job** [comment]
this was an off by one bug in exabgp.
