### ISSUE TITLE
do something better with control chars

### ISSUE THREAD

**Issue by job** [job/openbgpd#12]
We know that in 7 bit ascii chars < 32 are used as control chars rather then to communicate an actual message. Perhaps something smart can be done to dampen their effects

**Comment by Habbie** [comment]
Doesn't vis() cover this?

**Comment by job** [comment]
¯\_(ツ)_/¯

**Comment by job** [comment]
shouldn't be an issue: https://github.com/job/openbgpd/compare/openbgpd-import...master#diff-d25f51fc2de6f6d9065867547d903c9fR173
