### ISSUE TITLE
Show shutdown communication in syslog

### ISSUE THREAD

**Issue by job** [job/openbgpd#2]
Currently the syslog message looks like:

`Dec 14 10:09:08 kiera bgpd[99938]: neighbor 165.254.255.17: received notification: Cease, administratively down`

when a shutdown communication is received it could perhaps look like:

`Dec 14 10:09:08 kiera bgpd[99938]: neighbor 165.254.255.17: received notification: Cease, administratively down (shutdown communication: "henk is gek")`

**Comment by Habbie** [comment]
1ebde35c9723951315595b66d887e072a9980755 and friends dumbly dump it to stdout; just needs cleanup

**Comment by Habbie** [comment]
Done in f852af2f0f7f6341cb02e40df53508763d14adef
